# Generated by Django 3.0.8 on 2020-08-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('horas', models.IntegerField()),
                ('creditos', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
    ]
