# Generated by Django 3.0.8 on 2020-08-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFinalLP3', '0002_carrera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='carrera',
            name='fecha_fundacion',
            field=models.CharField(max_length=10),
        ),
    ]
